const {
  getAllLocations,
  insertLocation,
  updateLocation,
  deleteLocation,
  getAllTypes,
  insertType,
  updateType,
  deleteType,
  getAllSubtypes,
  insertSubtype,
  updateSubtype,
  deleteSubtype,
  validateLocation,
} = require('./queries')

module.exports = {
  getAllLocations,
  insertLocation,
  updateLocation,
  deleteLocation,
  getAllTypes,
  insertType,
  updateType,
  deleteType,
  getAllSubtypes,
  insertSubtype,
  updateSubtype,
  deleteSubtype,
  validateLocation,
}
